as3/accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views 
from .views import (
    LoginView,
    logout_view,
    profile_view,
    password_reset_request
)

app_name = 'account'

urlpatterns = [
    path("login/", LoginView.as_view(), name = "login"),
    path("logout/", logout_view, name = "logout"),
    path("profile/", profile_view, name = "profile"),
    
    path("password_reset", password_reset_request, name="password_reset"),
    path('password_reset/done/', 
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), 
         name='password_reset_done'
    ),
    path(
        'password_reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), 
        name='password_reset_confirm', 
    ),
    # path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),  
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth.views import PasswordResetCompleteView 
from django.conf import settings
from django.conf.urls.static import static
from as3.core.views.template import *

handler404 = 'as3.core.views.template.handler404'
handler500 = 'as3.core.views.template.handler500'
handler403 = 'as3.core.views.template.handler403'
handler400 = 'as3.core.views.template.handler400'

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('as3.core.urls')),
    path('accounts/', include('as3.accounts.urls', namespace='company-accounts')),
    path('admin/accounts/', include('as3.accounts.urls', namespace='admin-accounts')),
    path('password_reset/complete/', PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),  
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

as3/accounts/models.py
from django.db import models

# Create your models here.

as3/core/models/base.py
from config.celery import celery_app
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from .managers.user import UserManager


class Countries(models.Model):
    name = models.CharField(max_length=100, unique=True)
    units = models.CharField(max_length=100)
    active = models.BooleanField(default = True)
    class Meta:
        db_table = 'api_basic_countries'
        verbose_name = _('country')
        verbose_name_plural = _('countries')
    
class Users(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()
    profile = models.CharField(max_length = 63, choices=(
        ("Admin", "Admin"),
        ("Superadmin", "Superadmin"),
        ("Company", "Company"),
        ("Student", "Student"),
        ("Group", "Group"),
        ("Team", "Team"),
    ), null = True, db_column='profile', db_index = True)
    email = models.EmailField(_('Email Address'), db_index=True, unique=True)
    active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    name = models.CharField(max_length=150, null = True, blank = True)
    
    emailVerified = models.BooleanField(default = False)
    tokenExpired = models.BooleanField(default = False)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True, null = True, blank = True)
    idCountry = models.ForeignKey(Countries, on_delete=models.PROTECT, null = True, db_column='idCountry')
    phone = models.CharField(max_length=100, null = True, blank = True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    timestamp = models.DateTimeField(_('timestamp'), auto_now_add=True)
    objects = UserManager()
    
    USERNAME_FIELD = 'username'
    # REQUIRED_FIELDS = []

    class Meta:
        app_label = "core"
        db_table = 'api_basic_users'
        verbose_name = _('Users')
        verbose_name_plural = _('Users')

    def save(self, *args, **kwargs):
        if self.is_superuser:
            self.profile = "Superadmin"
        if self.profile == "Company":
            pass
        super(Users, self).save(*args, **kwargs)

    @celery_app.task(bind = True)
    def send_email(self, to_emails, subject, html_content, **kwargs):
        message = Mail(
            from_email='no-reply@as3international.com',
            to_emails= to_emails,
            subject=subject,
            html_content= html_content
        )
        try:
            sg = SendGridAPIClient(settings.SENDGRID_APIKEY)
            response = sg.send(message)
            print(response.status_code)
        except Exception as e:
            raise AssertionError('Invalid header found. {}'.format(e))

    @property
    def is_superadmin_profile(self):
        if self.profile == "Superadmin":
            return True
        return False
    
    @property
    def is_admin_profile(self):
        if self.profile == "Admin":
            return True
        return False

    @property
    def is_company_profile(self):
        if self.profile == "Company":
            return True
        return False

    @property
    def is_superadmin_or_admin(self):
        return self.is_superadmin_profile or self.is_admin_profile
                    
class Locations(models.Model):
    """
    This table is used to link the Team names.
    NOTE: Do not confuse Location table with Venue (for exercise venue)
    """
    address1 = models.CharField(max_length=120, null = True, blank = True)
    address2 = models.CharField(max_length=120, null = True, blank = True)
    city = models.CharField(max_length=100, null = True, blank = True)
    state = models.CharField(max_length=100, null = True, blank = True)
    idCountry = models.ForeignKey(Countries, on_delete=models.PROTECT, db_column='idCountry')
    active = models.BooleanField(default=True)
    
    @property
    def full_address(self):
        return self.address1 + " " + self.address2 + ' ' + self.city \
            + " " + self.state
    
    class Meta:
        db_table = 'api_basic_locations'
        verbose_name = _('location')
        verbose_name_plural = _('locations')

class Companies(models.Model):    
    name = models.CharField(max_length=180, unique=True)
    contact = models.CharField(max_length=100, null = True, blank = True)
    # idUser = models.OneToOneField(
        # Users, on_delete=models.PROTECT, null = True, db_column='idUser',
        # db_index=True, related_name="company")
    timestamp = models.DateTimeField(_('timestamp'), auto_now_add=True)
    active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    class Meta:
        db_table = 'api_basic_companies'
        verbose_name = _('company')
        verbose_name_plural = _('companies')
    
    def get_absolute_url(self):
        return reverse("core:index")
    
    def get_students_absolute_url(self):
        return reverse("core:students")


class CompanyUsers(models.Model):
    idCompany = models.ForeignKey(Companies, on_delete = models.PROTECT, db_index=True, db_column='idCompany')
    idUser = models.OneToOneField(Users, on_delete = models.PROTECT, db_index=True, db_column='idUser')
    class Meta:
        db_table = 'api_basic_company_users'
        verbose_name = _('company_users')

class Groups(models.Model):
    name = models.CharField(max_length=180, unique=True)
    description = models.TextField(null = True, blank = True)
    idCountry = models.ForeignKey(Countries, on_delete=models.PROTECT, null = True, db_column='idCountry')
    # idUser = models.OneToOneField(Users, on_delete=models.PROTECT, null = True, db_column='idUser', related_name="user_group")
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'api_basic_groups'
        verbose_name = _('group')
        verbose_name_plural = _('groups')

class GroupUsers(models.Model):
    idGroup = models.ForeignKey(Groups, on_delete = models.PROTECT, db_index=True)
    idUser = models.OneToOneField(Users, on_delete = models.PROTECT, db_index=True)
    class Meta:
        db_table = 'api_basic_group_users'
        verbose_name = _('group_users')
class Teams(models.Model):
    name = models.CharField(max_length=180, db_index=True, unique=True)
    idLocation = models.ForeignKey(Locations, on_delete=models.PROTECT, null = True, db_column='idCLocation')
    # idUser = models.OneToOneField(Users, on_delete=models.PROTECT, null = True, db_column='idUser')
    idCompany = models.ForeignKey(Companies, on_delete=models.PROTECT, null = True, db_column='idCompany')
    description = models.TextField(null = True, blank = True)
    active = models.BooleanField(default=True)
    
    class Meta:
        db_table = 'api_basic_teams'
        verbose_name = _('team')
        verbose_name_plural = _('teams')

class TeamUsers(models.Model):
    idTeam = models.ForeignKey(Teams, on_delete = models.PROTECT, db_index=True)
    idUser = models.OneToOneField(Users, on_delete = models.PROTECT, db_index=True)
    class Meta:
        db_table = 'api_basic_team_users'
        verbose_name = _('team_users')
  
class Students(models.Model):
    studentId = models.CharField(max_length=63, unique=True, db_index=True, blank = True)
    idUser = models.OneToOneField(Users, on_delete=models.PROTECT, null = True, db_column='idUser')
    email = models.EmailField(_('Email Address'),  null = True, blank = True)
    phone = models.CharField(max_length=100, null = True, blank = True)
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    active = models.BooleanField(default=True)
    gender = models.CharField(max_length=100, choices = (
        ("M", "Male"),
        ("F","Female"),
        ("NA", "Rather not say")
    ))
    birthday = models.DateField(null = True, blank = True)
    timestamp = models.DateTimeField(_('timestamp'), auto_now_add=True)
    
    class Meta:
        db_table = 'api_basic_students'
        verbose_name = _('student')
        verbose_name_plural = _('students')
        unique_together = (
            ("firstName", "lastName", "birthday")
        )
    def fullName(self):
        return f"{self.firstName} {self.lastName}"
    
class Programs(models.Model):
    name = models.CharField(max_length=100, unique=True, db_index = True)
    durationDays = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(_('timestamp'), auto_now_add=True)

    class Meta:
        db_table = 'api_basic_programs'
        verbose_name = _('program')
        verbose_name_plural = _('programs') 

class GroupStudents(models.Model):

as3/accounts/views.py
from as3.accounts.forms import AdminUserLoginForm, CompanyUserLoginForm
from as3.core.models import Users
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.db.models.query_utils import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views import View
from django.conf import settings
from django.shortcuts import render, get_object_or_404


class LoginView(View):
    @staticmethod
    def formclass(namespace):
        if namespace == 'company-accounts':
            return CompanyUserLoginForm
        elif namespace == 'admin-accounts':
            return AdminUserLoginForm
        
    @staticmethod
    def template(namespace):
        if namespace == 'company-accounts':
            return "accounts/company/login.html"
        elif namespace == 'admin-accounts':
            return "accounts/admin/login.html"
           
    def get(self, request, *_, **__):
        namespace = self.request.resolver_match.namespace
        if request.user.is_authenticated:
            return redirect("/")
        form = self.formclass(namespace)(request.POST or None)
        return render(request, self.template(namespace), {"form" : form})
    
    def post(self, request, *_, **__):
        namespace = self.request.resolver_match.namespace
        form = self.formclass(namespace)(request.POST or None)
        
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username = username, password = password)
            if not user and Users.objects.filter(email = username).exists():
                _username = Users.objects.get(email = username).username
                user = authenticate(username = _username, password = password)
            if not user:
                return render(request, self.template(namespace), {"form" : form}) 
            login(request, user)
            puser = get_object_or_404(Users, id = user.id)
            if puser.is_superadmin_or_admin:
                request.session["user-type"] = "admin"
                return redirect("core:admin:admin_index")
            else:
                request.session["user-type"] = "company"
                return redirect("core:index")
        else:
            return render(request, self.template(namespace), {"form" : form}) 
        
def logout_view(request):
    user_type = request.session.get("user-type")
    logout(request)
    if user_type == 'admin':
        return HttpResponseRedirect("/admin")
    return HttpResponseRedirect("/")


@login_required(login_url='/accounts/login/')
def profile_view(request):
	return HttpResponseRedirect("/")


def password_reset_request(request):
    ns = request.resolver_match.namespaces
    if ns and ns[0] != 'company-accounts':
        return redirect(reverse(f"{ns[0]}:login")) 
    
    template_name = "accounts/password/password_reset.html"
    
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            try:
                user = Users.objects.get(email=data)
            except Users.DoesNotExist as e:
                return HttpResponse('Invalid header found. {}'.format(e))
            
            if user.idCountry.name == "MX":
                email_template_name = "accounts/email/[es]password_reset_email.html"
                subject = "Restablece tu contraseña"
            else:
                email_template_name = "accounts/email/[en]password_reset_email.html"
                subject = "Reset your password"
            
            c = {
                "email":user.email,
                'domain':settings.DOMAIN,
                'site_name': 'as3international',
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "user": user,
                'token': default_token_generator.make_token(user),
                'protocol': 'http',
            }
            user.send_email.delay(
                subject = subject,
                html_content = render_to_string(email_template_name, c),
                to_emails= user.email,
            )
            return redirect (reverse("company-accounts:password_reset_done"))
                        
    password_reset_form = PasswordResetForm()
    return render(request, template_name, context={"password_reset_form":password_reset_form})
    
    

as3/templates/components/dashboard/admin/companies-table.html
<section class="section users-table">
    <div class="row" id="basic-table">
        <div class="col-12 col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <h4 class="card-title">Company Report </h4>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group position-relative has-icon-right ">
                            <input type="text" class="form-control filter-input" placeholder="Search here..." id = "id_company_search_input">
                            <div class="form-control-icon" style = "float:right;">
                                <i class="bi bi-search"></i>
                            </div>
                        </div>
                    </div>

                        <div class="col-6">
                            <div id="companies-table-pagination" style="float:right;">
                            </div>
                        </div>
                    </div>

                </div>

                <div class="card-content">
                    <div class="card-body">
                        <div class="table-responsive table-scrollable" id="companies-table"
                            data-url="{% url 'core:api:admin_api:company_report_list_api' %}">
                        </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
        {% include 'components/dashboard/admin/company-user-detail-modal.html' %}
</section>

as3/templates/components/dashboard/admin/company-user-detail-modal.html
<!-- Modal -->
<div class="modal fade" id="company-user-detail-modal" tabindex="-1" aria-labelledby="company-detail-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="company-detail-modal-label"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id = 'company-user-modal-body'>
        </div>
        <div class="modal-footer">
          {% comment %} <a role="button" class = "btn btn-primary" id = "detail_page_btn" target = "_blank">View Detail Page</a> {% endcomment %}
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

as3/templates/components/dashboard/admin/course-upload-table.html

<section class="section course-upload-table">
    {% include 'components/dashboard/admin/upload-course.html' %}
    <div class="row" id="basic-table">
        <div class="col-12 col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Uploaded Courses
                        <button style="" class="btn btn-primary float-right" id="" 
                        data-bs-toggle="offcanvas" data-bs-target="#uploadCourseOffcanvasBottom"
                        aria-controls="uploadCourseOffcanvasBottom">
                            New Course <i class="bi bi-cloud-plus-fill"></i>
                    </button>
                        <br>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <div id="course-upload-table" 
                        data-url="{% url 'core:api:admin_api:course_uploads_list' %}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>




   


as3/templates/components/dashboard/admin/create-basic-model-modal.html
<!-- Modal -->
<div class="modal fade" id="create-basic-model-modal" role="dialog" aria-labelledby="create-basic-model-modal-label"
	aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="create-basic-model-modal-label">Add New <span class = "model_data_type"></span></h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<form method="POST" class="needs-validation" 
			novalidate="" autocomplete="off" id="_id_basic_model_create_form"
			>
				<div class="modal-body">
					{% csrf_token %}
					<div class="form-group">
						<label for = "id_basic_model_input" style="margin-bottom:4px;"><span class = "model_data_type"></span> Name</label>
						<input class="form-control" name="name" id="id_basic_model_input" autofocus />
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
					<input type="submit" class="btn btn-primary" data-bs-dismiss="modal" value="Add">
				</div>
			</form>

		</div>
	</div>
</div>

as3/templates/components/dashboard/admin/create-edit-user-modal.html
<div class="modal fade" id="add-edit-user-modal" tabindex="-1" aria-labelledby="add-edit-user-modal-label"
	aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="add-edit-user-modal-label"><span class="user_createtype_head">Create new User</span> 
				</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<form id="admin_create_edit_form">{% csrf_token %}
				<div class="modal-body">
					<div class="mb-3">
						<label for="name" class="col-form-label">Name:</label>
						<input type="text" class="form-control" id="id_name" name = "name">
					</div>

					<div class="mb-3">
						<label for="name" class="col-form-label">Username:</label>
						<input type="text" class="form-control" id="id_username" name = "username" required>
					</div>

					<div class="mb-3">
						<label for="email" class="col-form-label">Email:</label>
						<input type="email" class="form-control" id="id_email" name = "email" required>
					</div>

					<div class="mb-3" id = "password-field">
						<label for="message-text" class="col-form-label">Password:</label>
						<input type="password" class="form-control" id="id_password" name = "password" required>
					</div>
					<div class="mb-3">
						<label for="profile" class="col-form-label">Profile:</label>
						<fieldset class="form-group">
							<select class="form-select"  id="id_profile" name = "profile" required>
								<option value="Admin">Admin</option>
								<option value="Company">Company</option>
								<option value="Group">Group</option>
								<option value="Team">Team</option>
								<option value="Student">Student</option>
							</select>
						</fieldset>
					</div>
					<div class="mb-3" id = "id_country_form_ele">
					<label for="company" class="col-form-label">Company:</label>
					<select class="form-select" id="id_user_company_select" disabled="disabled" name = "company">
						<option value = "-1" disabled="disabled" selected="true">No company selected</option>
						{% for company in companies %}
						<option value = {{company.id}}>{{company.name}}</option>
						{% endfor %}
					</select>
				</div>
					
					<div class="mb-3">
						<label for="country" class="col-form-label">Country:</label>
						<fieldset class="form-group">
							<select class="form-select" id="id_country" name = "country">
								{% for country in countries %}
								<option value="{{country.name}}">{{country.name}}</option>
								{% endfor %}
							</select>
						</fieldset>
					</div>

				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary" id = "submit-user"><span class="user_createtype_btn">Submit</span></button>
				</div>
			</form>

		</div>
	</div>
</div>

as3/templates/components/dashboard/admin/create-edit-vehicles-modal.html
<div class="modal fade" id="add-edit-vehicle-modal" tabindex="-1" aria-labelledby="add-edit-vehicle-modal-label"
	aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="add-edit-vehicle-modal-label"><span class="vehicle_createtype_head">Edit
						Vehicle</span>
				</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<form id="vehicle_create_edit_form" data-url="" enctype="multipart/form-data">{% csrf_token %}
				<div class="modal-body">
					<div class = "row">
						<div class="col-6">
							<label for="name" class="col-form-label">Name:</label>
							<input type="text" maxlength="100" class="form-control" id="id_vehicle_name" name="name">
						</div>
						<div class="col-6">
							<label for="name" class="col-form-label">Lat Acc</label>
							<input type="number" step="0.01" class="form-control" id="id_last_acc" name="latAcc">
						</div>
					</div>
					<div class = "row">
						<div class="col-6">
							<label for="name" class="col-form-label">Type:</label>
							<input type="text" maxlength="100" class="form-control" id="id_vehicle_type" name="type">
						</div>
						<div class="col-6">
							<label for="name" class="col-form-label">Make:</label>
							<input type="number" step="0.01" class="form-control" id="id_vehicle_make" name="make">
						</div>
					</div>
					<br>
					<div class="mb-3">
						<div class="vehicle-image-upload">
							<div class="vehicle-image-edit">
								<input type='file' id="id_vehicle_image" accept=".png, .jpg, .jpeg" name = "image" />
								<label for="id_vehicle_image">
									<i class="bi bi-image-fill" id = "vehicle-image-icon"></i>
								</label>
							</div>
							<div class="avatar-preview">
								<div id="vehicle-image-image-preview">
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
							<button type="submit" class="btn btn-primary" id="submit-edit-vehicle"><span
									class="vehicle_createtype_btn">Update Vehicle</span></button>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

as3/templates/components/dashboard/admin/users-table.html
<section class="section users-table">
    <div class="row" id="basic-table">
        <div class="col-12 col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Users 
                        <button type="button" class="btn btn-primary float-right " data-bs-toggle="modal"
                            data-bs-target="#add-edit-user-modal" id = "add-user-btn"
                            data-url="{% url 'core:api:admin_api:user_list_api' %}">
                            New User <i class="bi bi-person-plus-fill"></i>
                        </button></h4>
                        <br>
                    <div class="row">
                        <div class="col-4 col-lg-4 col-md-12 col-sm-12">
                            <h6>Search</h6>
                            <div class="form-group position-relative has-icon-right ">
                                <input type="text" class="form-control filter-input" placeholder="Search Anything here..." id = "id_user_search_input">
                              <div class="form-control-icon" style = "float:right;">
                                    <i class="bi bi-search"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-2 col-lg-2 col-md-4 col-sm-4">
                            <h6>Profile</h6>
                            <fieldset class="form-group">
                                <select class="form-select filter-input" id="profile-select">
                                    <option value="all">All</option>
                                    <option value="Superadmin">Super Admin</option>
                                    <option value="Admin">Admin</option>
                                    <option value="Company">Company</option>
                                    <option value="Group">Group</option>
                                    <option value="Team">Team</option>
                                    <option value="Student">Student</option>
                                </select>
                            </fieldset>
                        </div>

                        <div class="col-2 col-lg-2 col-md-4 col-sm-4">
                            <h6>Country</h6>
                            <fieldset class="form-group">
                                <select class="form-select filter-input" id="country-select">
                                    <option value="all">All</option>
                                    {% for country in countries %}
                                    <option value="{{country.name}}">{{country.name}}</option>
                                    {% endfor %}
                                </select>
                            </fieldset>
                        </div>

                        <div class = "col-4 col-lg-4 col-md-12 col-sm-12">
                            <div id = "user-table-pagination">
                            </div>
                        </div>
                    </div>

                </div>
                <div class="card-content">
                    <div class="card-body">
                        <div id="users-table" data-url="{% url 'core:api:admin_api:user_list_api' %}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'components/dashboard/admin/create-edit-user-modal.html' %}
</section>