as3/accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views 
from .views import (
    LoginView,
    logout_view,
    profile_view,
    password_reset_request
)

app_name = 'account'

urlpatterns = [
    path("login/", LoginView.as_view(), name = "login"),
    path("logout/", logout_view, name = "logout"),
    path("profile/", profile_view, name = "profile"),
    
    path("password_reset", password_reset_request, name="password_reset"),
    path('password_reset/done/', 
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), 
         name='password_reset_done'
    ),
    path(
        'password_reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), 
        name='password_reset_confirm', 
    ),
    # path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),  
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth.views import PasswordResetCompleteView 
from django.conf import settings
from django.conf.urls.static import static
from as3.core.views.template import *

handler404 = 'as3.core.views.template.handler404'
handler500 = 'as3.core.views.template.handler500'
handler403 = 'as3.core.views.template.handler403'
handler400 = 'as3.core.views.template.handler400'

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('as3.core.urls')),
    path('accounts/', include('as3.accounts.urls', namespace='company-accounts')),
    path('admin/accounts/', include('as3.accounts.urls', namespace='admin-accounts')),
    path('password_reset/complete/', PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),  
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

as3/accounts/models.py
from django.db import models

# Create your models here.

as3/core/models/base.py
from config.celery import celery_app
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from .managers.user import UserManager


class Countries(models.Model):
    name = models.CharField(max_length=100, unique=True)
    units = models.CharField(max_length=100)
    active = models.BooleanField(default = True)
    class Meta:
        db_table = 'api_basic_countries'
        verbose_name = _('country')
        verbose_name_plural = _('countries')
    
class Users(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()
    profile = models.CharField(max_length = 63, choices=(
        ("Admin", "Admin"),
        ("Superadmin", "Superadmin"),
        ("Company", "Company"),
        ("Student", "Student"),
        ("Group", "Group"),
        ("Team", "Team"),
    ), null = True, db_column='profile', db_index = True)
    email = models.EmailField(_('Email Address'), db_index=True, unique=True)
    active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    name = models.CharField(max_length=150, null = True, blank = True)
    
    emailVerified = models.BooleanField(default = False)
    tokenExpired = models.BooleanField(default = False)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True, null = True, blank = True)
    idCountry = models.ForeignKey(Countries, on_delete=models.PROTECT, null = True, db_column='idCountry')
    phone = models.CharField(max_length=100, null = True, blank = True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    timestamp = models.DateTimeField(_('timestamp'), auto_now_add=True)
    objects = UserManager()
    
    USERNAME_FIELD = 'username'
    # REQUIRED_FIELDS = []

    class Meta:
        app_label = "core"
        db_table = 'api_basic_users'
        verbose_name = _('Users')
        verbose_name_plural = _('Users')

    def save(self, *args, **kwargs):
        if self.is_superuser:
            self.profile = "Superadmin"
        if self.profile == "Company":
            pass
        super(Users, self).save(*args, **kwargs)

    @celery_app.task(bind = True)
    def send_email(self, to_emails, subject, html_content, **kwargs):
        message = Mail(
            from_email='no-reply@as3international.com',
            to_emails= to_emails,
            subject=subject,
            html_content= html_content
        )
        try:
            sg = SendGridAPIClient(settings.SENDGRID_APIKEY)
            response = sg.send(message)
            print(response.status_code)
        except Exception as e:
            raise AssertionError('Invalid header found. {}'.format(e))

    @property
    def is_superadmin_profile(self):
        if self.profile == "Superadmin":
            return True
        return False
    
    @property
    def is_admin_profile(self):
        if self.profile == "Admin":
            return True
        return False

    @property
    def is_company_profile(self):
        if self.profile == "Company":
            return True
        return False

    @property
    def is_superadmin_or_admin(self):
        return self.is_superadmin_profile or self.is_admin_profile
                    
class Locations(models.Model):
    """
    This table is used to link the Team names.
    NOTE: Do not confuse Location table with Venue (for exercise venue)
    """
    address1 = models.CharField(max_length=120, null = True, blank = True)
    address2 = models.CharField(max_length=120, null = True, blank = True)
    city = models.CharField(max_length=100, null = True, blank = True)
    state = models.CharField(max_length=100, null = True, blank = True)
    idCountry = models.ForeignKey(Countries, on_delete=models.PROTECT, db_column='idCountry')
    active = models.BooleanField(default=True)
    
    @property
    def full_address(self):
        return self.address1 + " " + self.address2 + ' ' + self.city \
            + " " + self.state
    
    class Meta:
        db_table = 'api_basic_locations'
        verbose_name = _('location')
        verbose_name_plural = _('locations')

class Companies(models.Model):    
    name = models.CharField(max_length=180, unique=True)
    contact = models.CharField(max_length=100, null = True, blank = True)
    # idUser = models.OneToOneField(
        # Users, on_delete=models.PROTECT, null = True, db_column='idUser',
        # db_index=True, related_name="company")
    timestamp = models.DateTimeField(_('timestamp'), auto_now_add=True)
    active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    class Meta:
        db_table = 'api_basic_companies'
        verbose_name = _('company')
        verbose_name_plural = _('companies')
    
    def get_absolute_url(self):
        return reverse("core:index")
    
    def get_students_absolute_url(self):
        return reverse("core:students")


class CompanyUsers(models.Model):
    idCompany = models.ForeignKey(Companies, on_delete = models.PROTECT, db_index=True, db_column='idCompany')
    idUser = models.OneToOneField(Users, on_delete = models.PROTECT, db_index=True, db_column='idUser')
    class Meta:
        db_table = 'api_basic_company_users'
        verbose_name = _('company_users')

class Groups(models.Model):
    name = models.CharField(max_length=180, unique=True)
    description = models.TextField(null = True, blank = True)
    idCountry = models.ForeignKey(Countries, on_delete=models.PROTECT, null = True, db_column='idCountry')
    # idUser = models.OneToOneField(Users, on_delete=models.PROTECT, null = True, db_column='idUser', related_name="user_group")
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'api_basic_groups'
        verbose_name = _('group')
        verbose_name_plural = _('groups')

class GroupUsers(models.Model):
    idGroup = models.ForeignKey(Groups, on_delete = models.PROTECT, db_index=True)
    idUser = models.OneToOneField(Users, on_delete = models.PROTECT, db_index=True)
    class Meta:
        db_table = 'api_basic_group_users'
        verbose_name = _('group_users')
class Teams(models.Model):
    name = models.CharField(max_length=180, db_index=True, unique=True)
    idLocation = models.ForeignKey(Locations, on_delete=models.PROTECT, null = True, db_column='idCLocation')
    # idUser = models.OneToOneField(Users, on_delete=models.PROTECT, null = True, db_column='idUser')
    idCompany = models.ForeignKey(Companies, on_delete=models.PROTECT, null = True, db_column='idCompany')
    description = models.TextField(null = True, blank = True)
    active = models.BooleanField(default=True)
    
    class Meta:
        db_table = 'api_basic_teams'
        verbose_name = _('team')
        verbose_name_plural = _('teams')

class TeamUsers(models.Model):
    idTeam = models.ForeignKey(Teams, on_delete = models.PROTECT, db_index=True)
    idUser = models.OneToOneField(Users, on_delete = models.PROTECT, db_index=True)
    class Meta:
        db_table = 'api_basic_team_users'
        verbose_name = _('team_users')
  
class Students(models.Model):
    studentId = models.CharField(max_length=63, unique=True, db_index=True, blank = True)
    idUser = models.OneToOneField(Users, on_delete=models.PROTECT, null = True, db_column='idUser')
    email = models.EmailField(_('Email Address'),  null = True, blank = True)
    phone = models.CharField(max_length=100, null = True, blank = True)
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    active = models.BooleanField(default=True)
    gender = models.CharField(max_length=100, choices = (
        ("M", "Male"),
        ("F","Female"),
        ("NA", "Rather not say")
    ))
    birthday = models.DateField(null = True, blank = True)
    timestamp = models.DateTimeField(_('timestamp'), auto_now_add=True)
    
    class Meta:
        db_table = 'api_basic_students'
        verbose_name = _('student')
        verbose_name_plural = _('students')
        unique_together = (
            ("firstName", "lastName", "birthday")
        )
    def fullName(self):
        return f"{self.firstName} {self.lastName}"
    
class Programs(models.Model):
    name = models.CharField(max_length=100, unique=True, db_index = True)
    durationDays = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(_('timestamp'), auto_now_add=True)

    class Meta:
        db_table = 'api_basic_programs'
        verbose_name = _('program')
        verbose_name_plural = _('programs') 

class GroupStudents(models.Model):

as3/accounts/views.py
from as3.accounts.forms import AdminUserLoginForm, CompanyUserLoginForm
from as3.core.models import Users
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.db.models.query_utils import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views import View
from django.conf import settings
from django.shortcuts import render, get_object_or_404


class LoginView(View):
    @staticmethod
    def formclass(namespace):
        if namespace == 'company-accounts':
            return CompanyUserLoginForm
        elif namespace == 'admin-accounts':
            return AdminUserLoginForm
        
    @staticmethod
    def template(namespace):
        if namespace == 'company-accounts':
            return "accounts/company/login.html"
        elif namespace == 'admin-accounts':
            return "accounts/admin/login.html"
           
    def get(self, request, *_, **__):
        namespace = self.request.resolver_match.namespace
        if request.user.is_authenticated:
            return redirect("/")
        form = self.formclass(namespace)(request.POST or None)
        return render(request, self.template(namespace), {"form" : form})
    
    def post(self, request, *_, **__):
        namespace = self.request.resolver_match.namespace
        form = self.formclass(namespace)(request.POST or None)
        
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username = username, password = password)
            if not user and Users.objects.filter(email = username).exists():
                _username = Users.objects.get(email = username).username
                user = authenticate(username = _username, password = password)
            if not user:
                return render(request, self.template(namespace), {"form" : form}) 
            login(request, user)
            puser = get_object_or_404(Users, id = user.id)
            if puser.is_superadmin_or_admin:
                request.session["user-type"] = "admin"
                return redirect("core:admin:admin_index")
            else:
                request.session["user-type"] = "company"
                return redirect("core:index")
        else:
            return render(request, self.template(namespace), {"form" : form}) 
        
def logout_view(request):
    user_type = request.session.get("user-type")
    logout(request)
    if user_type == 'admin':
        return HttpResponseRedirect("/admin")
    return HttpResponseRedirect("/")


@login_required(login_url='/accounts/login/')
def profile_view(request):
	return HttpResponseRedirect("/")


def password_reset_request(request):
    ns = request.resolver_match.namespaces
    if ns and ns[0] != 'company-accounts':
        return redirect(reverse(f"{ns[0]}:login")) 
    
    template_name = "accounts/password/password_reset.html"
    
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            try:
                user = Users.objects.get(email=data)
            except Users.DoesNotExist as e:
                return HttpResponse('Invalid header found. {}'.format(e))
            
            if user.idCountry.name == "MX":
                email_template_name = "accounts/email/[es]password_reset_email.html"
                subject = "Restablece tu contraseña"
            else:
                email_template_name = "accounts/email/[en]password_reset_email.html"
                subject = "Reset your password"
            
            c = {
                "email":user.email,
                'domain':settings.DOMAIN,
                'site_name': 'as3international',
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "user": user,
                'token': default_token_generator.make_token(user),
                'protocol': 'http',
            }
            user.send_email.delay(
                subject = subject,
                html_content = render_to_string(email_template_name, c),
                to_emails= user.email,
            )
            return redirect (reverse("company-accounts:password_reset_done"))
                        
    password_reset_form = PasswordResetForm()
    return render(request, template_name, context={"password_reset_form":password_reset_form})
    
    

as3/templates/accounts/password/base.html
{% extends 'base.html' %}
{% load static %}

{% block base_styles %}
<link rel="stylesheet" href="{% static 'assets/css/auth.css' %}">
{% endblock base_styles %}

{% block base_content %}
<div id="auth">
    <div class="container h-100">
        <div class="row justify-content-sm-center h-100">
            <div class="col-xxl-5 col-xl-6 col-lg-6 col-md-7 col-sm-9">
                <div class="text-center my-5">
                    <img src="{% static 'assets\images\AS3-Driver-Training-Logo-small_93756138-d10c-421b-aa3d-190628bbbf74.png' %}"
                        alt="logo">
                </div>
                <div class = "card shadow-lg">
                    {% comment %} <div class = "card-header">
                        <h2 class="fs-4 card-title fw-bold mb-3 ">Login</h2>
                    </div> {% endcomment %}
                    <div class="card-body p-5">

                    {% block page_content %}
                    {% endblock page_content %}
                    </div>
                </div>
            </div>
        </div>
        {% comment %} <div class="col-lg-6 col-xl-6 col-xxl-7 d-none d-lg-block">
            <div id="auth-right" style="height: 100%; width: 100%;">
            </div>
        </div> {% endcomment %}
    </div>
</div>
{% endblock base_content %}
{% block base_js %}
{% block js %}
{% endblock %}
{% endblock %}

as3/templates/accounts/password/password_reset.html
{% extends 'accounts/password/base.html' %}
{% block title %}
<title>AS3 International Dashboard</title>
{% endblock title %}
{% block page_content %}
<!--Reset Password-->
<h2 class="auth-title">Forgot Password</h2>
<p class="auth-subtitle mb-3">Input your email and we will send you reset password link.</p>
{% comment %} <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a
	new one.</p> {% endcomment %}
{% for error in password_reset_form.email.errors %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
	<p>{{ error }}</p>
</div>
{% endfor %}

<form method="POST">
	{% csrf_token %}
	<div class="form-group position-relative has-icon-left mb-4">
		{{ password_reset_form.email }}
		<div class="form-control-icon">
			<i class="bi bi-envelope"></i>
		</div>
	</div>
	<button class="btn btn-primary btn-block btn-lg shadow-lg mt-3" type="submit">Send</button>
</form>
<div class="text-center mt-5 fs-5">
	<p class='text-gray-200'>Remember your account? <a href="{% url 'account:login' %}" class="font-bold">Log
			in</a>.
	</p>
</div>

{% endblock page_content %}

{% block js %}

<script>
	$("#id_email").addClass("form-control form-control-xl")
	$("#id_email").attr("placeholder", "Enter your email")
</script>
{% endblock js %}

as3/templates/accounts/password/password_reset_complete.html
{% extends 'accounts/password/base.html' %}
{% block title %}
<title>AS3 International Dashboard </title>
{% endblock title %}
{% block page_content %}
<!--Reset Password-->
<div>
	  <!--Password Reset Complete-->
    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>                 
        <a href="{% url 'company-accounts:login' %}" class="btn btn-primary">Go to Login</a>
        <p class = "mt-3">For admin, login from <a href="{% url 'admin-accounts:login' %}">here</a>.
    </div>
</div>

{% endblock page_content %}

as3/templates/accounts/password/password_reset_confirm.html
{% extends 'accounts/password/base.html' %}
{% load i18n %}
{% block title %}
<title>AS3 International Dashboard </title>
{% endblock title %}
{% block page_content %}
<div>
    <div class="row">
            {% if validlink %}
            <h2>{% trans 'Enter new password' %}</h2>
            <p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

            <form action="" method="post">{% csrf_token %}
                {% for error in form.new_password1.errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <p>{{ error }}</p>
                </div>
                {% endfor %}

                {% for error in form.new_password2.errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <p>{{ error }}</p>
                </div>
                {% endfor %}

                <div class="form-group mt-2 position-relative has-icon-left">
                    <label for="id_new_password1">{% trans 'New password:' %}</label>
                    <input class="form-control form-control-xl" type="password" id="id_new_password1" name="new_password1" value="">
                    <div class="form-control-icon" style = "margin-top: 12px;">
                        <i class="bi bi-shield-lock"></i>
                    </div>
                </div>

                <div class="form-group mt-2 position-relative has-icon-left">
                    <label for="id_new_password2">{% trans 'Confirm password:' %}</label>
                    <input class="form-control form-control-xl" type="password" id="id_new_password2" name="new_password2" value="">
                    <div class="form-control-icon" style = "margin-top: 12px;">
                        <i class="bi bi-shield-lock"></i>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-l2 mt-4">
                        <input type="submit" class="btn btn-primary btn-block btn-lg shadow-lg" value="{% trans 'Change my password' %}" />
                    </div>
                </div>
            </form>

            {% else %}

            <h1>{% trans 'Password reset unsuccessful' %}</h1>

            <p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}
            </p>

            {% endif %}
    </div>
</div>

{% endblock page_content %}

as3/templates/accounts/password/password_reset_done.html
{% extends 'accounts/password/base.html' %}
{% block title %}
<title>AS3 International Dashboard </title>
{% endblock title %}
{% block page_content %}
<!--Password reset sent-->
<div>
	<h2 class="font-weight-bold mt-3">Password reset sent</h2>
	<hr>
	<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You
		should receive them shortly.
		<br>If you don't receive an email, please make sure you've entered the address you registered with, and check
		your spam folder.</p>
</div>

{% endblock page_content %}