as3/accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views 
from .views import (
    LoginView,
    logout_view,
    profile_view,
    password_reset_request
)

app_name = 'account'

urlpatterns = [
    path("login/", LoginView.as_view(), name = "login"),
    path("logout/", logout_view, name = "logout"),
    path("profile/", profile_view, name = "profile"),
    
    path("password_reset", password_reset_request, name="password_reset"),
    path('password_reset/done/', 
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), 
         name='password_reset_done'
    ),
    path(
        'password_reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), 
        name='password_reset_confirm', 
    ),
    # path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),  
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth.views import PasswordResetCompleteView 
from django.conf import settings
from django.conf.urls.static import static
from as3.core.views.template import *

handler404 = 'as3.core.views.template.handler404'
handler500 = 'as3.core.views.template.handler500'
handler403 = 'as3.core.views.template.handler403'
handler400 = 'as3.core.views.template.handler400'

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('as3.core.urls')),
    path('accounts/', include('as3.accounts.urls', namespace='company-accounts')),
    path('admin/accounts/', include('as3.accounts.urls', namespace='admin-accounts')),
    path('password_reset/complete/', PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),  
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

as3/accounts/models.py
from django.db import models

# Create your models here.

as3/accounts/views.py
from as3.accounts.forms import AdminUserLoginForm, CompanyUserLoginForm
from as3.core.models import Users
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.db.models.query_utils import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views import View
from django.conf import settings
from django.shortcuts import render, get_object_or_404


class LoginView(View):
    @staticmethod
    def formclass(namespace):
        if namespace == 'company-accounts':
            return CompanyUserLoginForm
        elif namespace == 'admin-accounts':
            return AdminUserLoginForm
        
    @staticmethod
    def template(namespace):
        if namespace == 'company-accounts':
            return "accounts/company/login.html"
        elif namespace == 'admin-accounts':
            return "accounts/admin/login.html"
           
    def get(self, request, *_, **__):
        namespace = self.request.resolver_match.namespace
        if request.user.is_authenticated:
            return redirect("/")
        form = self.formclass(namespace)(request.POST or None)
        return render(request, self.template(namespace), {"form" : form})
    
    def post(self, request, *_, **__):
        namespace = self.request.resolver_match.namespace
        form = self.formclass(namespace)(request.POST or None)
        
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username = username, password = password)
            if not user and Users.objects.filter(email = username).exists():
                _username = Users.objects.get(email = username).username
                user = authenticate(username = _username, password = password)
            if not user:
                return render(request, self.template(namespace), {"form" : form}) 
            login(request, user)
            puser = get_object_or_404(Users, id = user.id)
            if puser.is_superadmin_or_admin:
                request.session["user-type"] = "admin"
                return redirect("core:admin:admin_index")
            else:
                request.session["user-type"] = "company"
                return redirect("core:index")
        else:
            return render(request, self.template(namespace), {"form" : form}) 
        
def logout_view(request):
    user_type = request.session.get("user-type")
    logout(request)
    if user_type == 'admin':
        return HttpResponseRedirect("/admin")
    return HttpResponseRedirect("/")


@login_required(login_url='/accounts/login/')
def profile_view(request):
	return HttpResponseRedirect("/")


def password_reset_request(request):
    ns = request.resolver_match.namespaces
    if ns and ns[0] != 'company-accounts':
        return redirect(reverse(f"{ns[0]}:login")) 
    
    template_name = "accounts/password/password_reset.html"
    
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            try:
                user = Users.objects.get(email=data)
            except Users.DoesNotExist as e:
                return HttpResponse('Invalid header found. {}'.format(e))
            
            if user.idCountry.name == "MX":
                email_template_name = "accounts/email/[es]password_reset_email.html"
                subject = "Restablece tu contraseña"
            else:
                email_template_name = "accounts/email/[en]password_reset_email.html"
                subject = "Reset your password"
            
            c = {
                "email":user.email,
                'domain':settings.DOMAIN,
                'site_name': 'as3international',
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "user": user,
                'token': default_token_generator.make_token(user),
                'protocol': 'http',
            }
            user.send_email.delay(
                subject = subject,
                html_content = render_to_string(email_template_name, c),
                to_emails= user.email,
            )
            return redirect (reverse("company-accounts:password_reset_done"))
                        
    password_reset_form = PasswordResetForm()
    return render(request, template_name, context={"password_reset_form":password_reset_form})
    
    

as3/core/api/views/admin.py
import ast
import json
import logging
import sys
import traceback
import timeago
import shortuuid
from as3.core.api.permissions import AdminOnlyPermission
from as3.core.api.serializers import VehiclesSerializer
from as3.core.db_utils.db_populate import CourseDataUploader
from as3.core.models import *
from as3.core.api.views.utils import send_welcome_email
from config.celery import celery_app
from django.db import connection, transaction
from django.db.models import Q
from django.urls import reverse
from rest_framework import status
from rest_framework.generics import ListAPIView
from rest_framework.pagination import LimitOffsetPagination
from rest_framework.response import Response
from rest_framework.views import APIView

logger = logging.getLogger(__name__)

# TODO  save user depending on the profile. Only partially company is done

class UserAPIView(APIView):
    permission_classes = (AdminOnlyPermission,)
    
    def get(self, request, pk):
        if not Users.objects.filter(id = pk).exists():
            return Response(status = 404)
        user = Users.objects.get(id = pk)
        puser = Users.objects\
            .filter(active = True)

        if not puser.exists():
            return Response(status = 404)
            
        puser = puser.values_list(
            "profile", "username", "active", "name", "idCountry__name", "id")
        user = {
            "id": puser[0][5],
            "username": puser[0][1],
            "name": puser[0][3],
            "country": puser[0][4],
            "profile": [u[0] for u in puser]
        }
        return Response(data = user, status = 200)
    
    def delete(self, request, pk):
        try:
            user = Users.objects.get(id = pk)
            if request.user == user: # self record can't be deleted
                return Response(data = {"status": "error", "error": f"You don't have permission to delete this record" }, status = 400)
            # admin can't be delete superadmin profile
            if user.is_superadmin_profile and not request.user.is_superadmin_profile:
                return Response(data = {"status": "error", "error": f"You don't have permission to delete this record" }, status = 400)
            
            with transaction.atomic():
                CompanyUsers.objects.filter(idUser = user).delete()
                user.delete()
            
            return Response(data = {"status": "success"}, status = 200)
        except Users.DoesNotExist:
            return Response(data = {"status": "error", "error": "User does not exists"}, status = 500)
        except Exception as e:
            return Response(data = {"status": "error", "error": str(e)}, status = 500)
            
    def put(self, request, pk):
        data = dict(request.data)
        profile = data.get("profile", [])
        country = data.get("country", [])
        company_id = data.get("company", [])
        name = data.get("name", [])
        email = data.get("email", [])
        # todo
        if not profile or len(profile) != 1:
            return Response(data = {"status": "error", "error": "User should have a profile"}, status = 400)
        try:
            with transaction.atomic():
                user = Users.objects.get(id = pk)
                if user.is_superadmin_profile and not request.user.is_superadmin_profile:
                    return Response(
                        data = {"status": "error", 
                                "error": f"You don't have permission to edit this record" 
                        }, status = 400
                    )
                if user == request.user and not user.is_superadmin_profile:
                    return Response(
                        data = {"status": "error", 
                                "error": f"You don't have permission to edit this record" 
                        }, status = 400
                    )
                if email:   user.email = email[0]
                if name:    user.name = name[0]
                if country: user.idCountry = Countries.objects.get(name__icontains = country[0])
                if profile: user.profile = profile[0]
                try:
                    user.save()
                except Exception as e:
                    return Response(
                        data = {"status": "error", 
                                "error": f"Problem in updating user: Error code: 400. {str(e)}"
                            }, status = 400
                    )
                try:
                    # unlink the old user associated with company 
                    if CompanyUsers.objects.filter(idUser = user).exists():
                        CompanyUsers.objects.filter(idUser = user).delete()
                    
                    if company_id and Companies.objects.filter(id = company_id[0]).exists():
                        company = Companies.objects.get(id = company_id[0])
                        if not CompanyUsers.objects.filter(idUser = user, idCompany = company):
                            CompanyUsers.objects.create(idUser = user, idCompany = company)
                except Exception as e:
                    print(e)
                    return Response(
                        data = {"status": "error", 
                            "error": f"Problem in updating/deleting profile: Error code: 400. {str(e)}"
                        }, status = 400
                    )
            return Response(data = {"status": "success"}, status = 200)
        except Exception as e:
            print(str(e))
            return Response(data = {"status": "error", "error": str(e)}, status = 500)
        
class UsersListAPIView(APIView):
    permission_classes = (AdminOnlyPermission,)

    def get(self, request):
        serialized_out = self.__get_queryset(request)
        data = {
            "items": serialized_out,
        }
        return Response(data = data, status = 200)            
    
    def post(self, request):
        try:
            data = dict(request.POST)
            profile = data.get("profile", [])
            username = data.get("username")
            email = data.get("email")
            password = data.get("password")

            if not profile or len(profile) != 1:
                return Response(data = {"status": "error", "error": "User should have a profile"}, status = 400)
            if Users.objects.filter(Q(username = data.get("username")[0]) | Q(email = data.get("email")[0])).exists():
                return Response(data = {"status": "error", "error": "User with this username/email already exists."}, status = 400)
            if not username:
                return Response(data = {"status": "error", "error": "Please provide username"}, status = 400)
            if not email:
                return Response(data = {"status": "error", "error": "Please provide email"}, status = 400)
            if not password:
                return Response(data = {"status": "error", "error": "Please provide Password"}, status = 400)

            with transaction.atomic():
                user = Users(
                    username = username[0],
                    email = email[0],
                    name = data.get("name")[0],
                    idCountry = Countries.objects.get(name__icontains = data.get("country")[0]),
                    profile = profile[0]
                )
                user.set_password(password[0])
                user.save()
                company_id = data.get("company", None)
                if company_id and Companies.objects.filter(id = company_id[0]).exists():
                    company = Companies.objects.get(id = company_id[0])
                    if not CompanyUsers.objects.filter(idUser = user, idCompany = company):
                        CompanyUsers.objects.create(idUser = user, idCompany = company)
                send_welcome_email(user)    
            return Response(data = {"status": "success"}, status = 201)
        except Exception as e:
            print(e)
            return Response(data = {"status": "error", "error": str(e)}, status = 500)
    
    def __get_users(self, profile_users):
        users = []
        profile_users = profile_users.values_list(
            "id", "profile", "username", "active",
            "name", "idCountry__name", "email", "last_login"
        )
        for user in profile_users:
            last_login = None
            if user[7]:
                last_login = timeago.format(user[7].replace(tzinfo=None))
            user_related_obj = None
            if user[1] == "Company":
                comp = CompanyUsers.objects.filter(idUser = user[0])
                if comp.exists():   user_related_obj = comp[0].idCompany
            users.append({
                "id": user[0],
                "profile": user[1],
                "username": user[2],
                "active": user[3],
                "name": user[4],
                "country": user[5],
                "email": user[6],
                "company": {
                    "id": user_related_obj.id if user_related_obj else None,
                    "name": user_related_obj.name if user_related_obj else None,
                },
                "last_login": last_login
            })
        return users
    
    def __get_queryset(self, request):
        profile = request.query_params.get('profile', None)
        country = request.query_params.get('country', None)
        profile_users = Users.objects\
            .select_related("idCountry",)\
            .all()
        if country and not country == "all":
            try:
                country_obj = Countries.objects.get(name = country)
            except Countries.DoesNotExist:  return []

as3/templates/partials/messages.html
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible shadow fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message | safe }}
    </div>
{% endfor %}


as3/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-light" style="margin-bottom: 20px;">
    <div class="container-fluid d-block">
        {% comment %} <a href="index.html"><i class="bi bi-chevron-left"></i></a> {% endcomment %}
        <a class="" href="/">
            <img class="img-responsive img-fluid"
                src="{% static 'assets\images\AS3-Driver-Training-Logo-small_93756138-d10c-421b-aa3d-190628bbbf74.png' %}">
        </a>
        <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
            <div class="dropdown" style="float:right;">
                <div class="user-menu d-flex">
                    <div class="user-name text-end me-3">
                        <h6 class="mb-0 text-gray-600">{{request.user.username}}</h6>
                        <p class="mb-0 text-sm text-gray-600">
                            {% if request.user.profile == "Admin" or request.user.profile == "Superadmin"  %}{{request.user.profile}}{% else %}{{company.name}}{% endif %}</p>
                    </div>
                    <div class="user-img d-flex align-items-center">
                        <div class="avatar avatar-md">
                            <img src="{% static 'assets/images/avatar.png' %}">
                        </div>
                    </div>
                </div>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton"
                    style="min-width: 11rem;">
                    {% comment %} <li>
                        <h6 class="dropdown-header">Hello, {{request.user.username}}!</h6>
                    </li> {% endcomment %}

                    {% if user_type == "company" %}
                    <li><a class="dropdown-item" href="/feedback">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-send-fill" viewBox="0 0 16 16">
                                <path
                                    d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 3.178 4.995.002.002.26.41a.5.5 0 0 0 .886-.083l6-15Zm-1.833 1.89L6.637 10.07l-.215-.338a.5.5 0 0 0-.154-.154l-.338-.215 7.494-7.494 1.178-.471-.47 1.178Z" />
                            </svg> Feedback</a>
                    </li>
                    {% endif %}

                    {% comment %} <li><a class="dropdown-item" href="#"><i class="icon-mid bi bi-person me-2"></i> My
                            Profile</a></li>
                    <li><a class="dropdown-item" href="#"><i class="icon-mid bi bi-gear me-2"></i>Settings</a></li>
                    {% endcomment %}
                    <hr class="dropdown-divider">
                    <li><a class="dropdown-item" href="{% url 'account:logout' %}"><i
                                class="icon-mid bi bi-box-arrow-left me-2"></i>Logout</a></li>
                </ul>
            </div>
        </a>
        <div style="float: right;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-translate"
                viewBox="0 0 16 16" style="margin-top:5px;margin-right:4px;">
                <path
                    d="M4.545 6.714 4.11 8H3l1.862-5h1.284L8 8H6.833l-.435-1.286H4.545zm1.634-.736L5.5 3.956h-.049l-.679 2.022H6.18z" />
                <path
                    d="M0 2a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v3h3a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-3H2a2 2 0 0 1-2-2V2zm2-1a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h7a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H2zm7.138 9.995c.193.301.402.583.63.846-.748.575-1.673 1.001-2.768 1.292.178.217.451.635.555.867 1.125-.359 2.08-.844 2.886-1.494.777.665 1.739 1.165 2.93 1.472.133-.254.414-.673.629-.89-1.125-.253-2.057-.694-2.82-1.284.681-.747 1.222-1.651 1.621-2.757H14V8h-3v1.047h.765c-.318.844-.74 1.546-1.272 2.13a6.066 6.066 0 0 1-.415-.492 1.988 1.988 0 0 1-.94.31z" />
            </svg>
            <select class="choices form-select choices__input" id="language-select"
                data-url="{% url 'core:api:language_change' %}">

                <option value="en"><i class="bi bi-funnel"></i>EN</option>
                <option value="es">ES</option>
            </select>

        </div>

    </div>
</nav>